# This is a basic workflow to help you get started with Actions

name: build-exe

# Controls when the workflow will run
on:
  release:
    types: [published]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-macos:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python3 
        uses: actions/setup-python@v2
        
      - name: Install virtualenv & pyinstaller
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          pip install pyinstaller
          
      - name: Create and use virtualenv
        run: |
          virtualenv env-macos
          source env-macos/bin/activate
          
      - name: Create and use virtualenv
        run: |  
          pip install -r requirements.txt
        
      - name: Package
        run: |
          pyinstaller --windowed -n easy-tick-windows.exe main.py

